### ISSUE TITLE
Bug in Linux OS

### ISSUE THREAD

**Issue by benshimonz** [halil/string-builder#10]
I think there is a bug in this function

```
StringBuilder.prototype.appendLine = function (v) {
  this.s.push("\r\n");
  if (v) {
    this.s.push(v);
  }
  return this;
};
```

**\r\n** will work in Windows OS, while in Linux this will cause problems (by adding '\r')

**Comment by halil** [comment]
@benshimonz thanks for feedback. Issue fixed.
